import { db } from "./firebase.js";
import { ref,get,push,set,onValue,remove } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";
import { drawLadder,getPath,formatRemaining } from "./ladder-common.js";
const params=new URLSearchParams(location.search),room=params.get("room"),nickname=(params.get("nickname")||sessionStorage.getItem("nickname")||"").trim();const roomNumberEl=document.getElementById("roomNumber"),joinStatus=document.getElementById("joinStatus"),usersEl=document.getElementById("users"),userCountEl=document.getElementById("userCount"),statusEl=document.getElementById("ladderStatus"),canvas=document.getElementById("ladderCanvas"),resultArea=document.getElementById("resultArea"),timerEl=document.getElementById("roomTimer");let currentRoomData=null,registeredKey=sessionStorage.getItem("userKey:"+room);roomNumberEl.textContent=room??"-";
if(!room||!nickname){alert("방 번호 또는 이름이 없습니다.");location.href="./join-room.html";}else init();
async function init(){const roomRef=ref(db,"rooms/"+room);const s=await get(roomRef);if(!s.exists()){alert("존재하지 않는 방입니다.");location.href="./join-room.html";return;}const d=s.val();if(d.expireAt&&Date.now()>=d.expireAt){alert("이미 종료된 방입니다.");location.href="./join-room.html";return;}if(!registeredKey){const dup=Object.values(d.users||{}).some(u=>u.name===nickname);if(dup){alert("같은 이름이 이미 있습니다. 다른 이름을 사용해 주세요.");location.href="./join-room.html";return;}const userRef=push(ref(db,"rooms/"+room+"/users"));registeredKey=userRef.key;await set(userRef,{name:nickname,role:"guest",joinedAt:Date.now()});sessionStorage.setItem("userKey:"+room,registeredKey);sessionStorage.setItem("joinedRoom",room);sessionStorage.setItem("nickname",nickname);}joinStatus.textContent="✅ "+nickname+"님 참가 완료";onValue(roomRef,snap=>{if(!snap.exists()){alert("방이 종료되었습니다.");location.href="./index.html";return;}currentRoomData=snap.val();renderUsers(currentRoomData.users||{});renderLadder(currentRoomData.ladder||null);if(currentRoomData.expireAt)timerEl.textContent=formatRemaining(currentRoomData.expireAt);});startTimer();}
function renderUsers(obj){const users=Object.values(obj).sort((a,b)=>(a.joinedAt||0)-(b.joinedAt||0));userCountEl.textContent=users.length+"명";usersEl.innerHTML=users.map((u,i)=>{const me=u.name===nickname;return `<button class="user-chip ${me?"me":""}" ${me?'data-me="true"':""}><span>${i+1}</span><strong>${escapeHtml(u.name)}</strong>${me?"<em>나</em>":""}</button>`}).join("");const myBtn=usersEl.querySelector('[data-me="true"]');if(myBtn)myBtn.addEventListener("click",showMyPath);}
function renderLadder(l){if(!l){statusEl.textContent="방장이 사다리를 생성할 때까지 기다려 주세요.";drawLadder(canvas,[],[]);resultArea.innerHTML="";return;}statusEl.textContent="🎲 사다리가 생성되었습니다. 내 이름을 눌러 경로를 확인하세요.";drawLadder(canvas,l.bridges||[],l.users||[]);}
function showMyPath(){const l=currentRoomData?.ladder;if(!l){alert("아직 사다리가 생성되지 않았습니다.");return;}const idx=l.users.indexOf(nickname);if(idx<0){alert("현재 사다리에서 참가자를 찾을 수 없습니다.");return;}const path=getPath(idx,l.bridges||[]),finalIndex=path[path.length-1];drawLadder(canvas,l.bridges||[],l.users||[],idx);resultArea.innerHTML=`<div class="result-card"><strong>${escapeHtml(nickname)}</strong>님의 이동 경로<span>${path.map(v=>v+1).join(" → ")}</span><small>도착 위치: ${finalIndex+1}번</small></div>`;}
function startTimer(){const id=setInterval(async()=>{if(!currentRoomData?.expireAt)return;timerEl.textContent=formatRemaining(currentRoomData.expireAt);if(Date.now()>=currentRoomData.expireAt){clearInterval(id);try{await remove(ref(db,"rooms/"+room));}catch(e){console.error(e);}alert("방 생성 후 5분이 지나 자동 종료되었습니다.");location.href="./index.html";}},1000);}
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
