import { db } from "./firebase.js";
import { ref,get,update,onValue,remove } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";
import { generateLadder,calculateResults,drawLadder,formatRemaining } from "./ladder-common.js";
const params=new URLSearchParams(location.search),room=params.get("room"),hostToken=sessionStorage.getItem("hostToken"),hostRoom=sessionStorage.getItem("hostRoom");const roomNumberEl=document.getElementById("roomNumber"),usersEl=document.getElementById("users"),userCountEl=document.getElementById("userCount"),createBtn=document.getElementById("createLadderBtn"),statusEl=document.getElementById("ladderStatus"),canvas=document.getElementById("ladderCanvas"),resultArea=document.getElementById("resultArea"),timerEl=document.getElementById("roomTimer");let currentUsers=[],currentRoomData=null;roomNumberEl.textContent=room??"-";
if(!room||hostRoom!==room||!hostToken){alert("방장 정보가 없습니다. 방을 다시 만들어 주세요.");location.href="./create-room.html";}else init();
async function init(){const roomRef=ref(db,"rooms/"+room);const s=await get(roomRef);if(!s.exists()){alert("존재하지 않는 방입니다.");location.href="./create-room.html";return;}if(s.val().hostToken!==hostToken){alert("방장 권한을 확인할 수 없습니다.");location.href="./index.html";return;}onValue(roomRef,snap=>{if(!snap.exists()){alert("방이 종료되었습니다.");location.href="./index.html";return;}currentRoomData=snap.val();renderUsers(currentRoomData.users||{});renderLadder(currentRoomData.ladder||null);createBtn.disabled=currentUsers.length<2||currentRoomData.status!=="waiting";});createBtn.addEventListener("click",createLadder);startTimer();}
function renderUsers(obj){currentUsers=Object.values(obj).sort((a,b)=>(a.joinedAt||0)-(b.joinedAt||0)).map(u=>u.name);userCountEl.textContent=currentUsers.length+"명";usersEl.innerHTML=currentUsers.length?currentUsers.map((n,i)=>`<div class="user-chip"><span>${i+1}</span><strong>${escapeHtml(n)}</strong></div>`).join(""):`<div class="empty-state">참가자를 기다리는 중입니다.</div>`;}
function renderLadder(l){if(!l){statusEl.textContent=currentUsers.length<2?"참가자 2명 이상이 필요합니다.":"참가자가 모두 모이면 사다리를 생성하세요.";drawLadder(canvas,[],currentUsers);resultArea.innerHTML="";return;}statusEl.textContent="🎲 모든 화면에 동일한 사다리가 표시됩니다.";drawLadder(canvas,l.bridges||[],l.users||[]);resultArea.innerHTML='<div class="result-card">사다리 생성 완료! 참가자는 자신의 이름을 눌러 경로를 확인할 수 있습니다.</div>';}
async function createLadder(){if(currentUsers.length<2)return;const bridges=generateLadder(currentUsers.length),results=calculateResults(currentUsers.length,bridges);await update(ref(db,"rooms/"+room),{status:"ladder_created",ladder:{users:currentUsers,bridges,results,createdAt:Date.now()}});}
function startTimer(){const id=setInterval(async()=>{if(!currentRoomData?.expireAt)return;timerEl.textContent=formatRemaining(currentRoomData.expireAt);if(Date.now()>=currentRoomData.expireAt){clearInterval(id);try{await remove(ref(db,"rooms/"+room));}catch(e){console.error(e);}alert("방 생성 후 5분이 지나 자동 종료되었습니다.");location.href="./index.html";}},1000);}
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
